import { PremiumCar, Testimonial } from "./types";

export const BRAND_STATS = [
  { label: "Elite Members", value: "1,200+", increment: 10 },
  { label: "Custom Builds", value: "185+", increment: 2 },
  { label: "Track Records", value: "14", increment: 1 },
  { label: "Global Showrooms", value: "24", increment: 1 },
];

export const WHY_CHOOSE_US_DATA = [
  {
    id: "certified",
    title: "Rigorous Validation",
    description: "Every bespoke model undergoes an exhaustive diagnostic process and track testing.",
    icon: "ShieldAlert",
  },
  {
    id: "global",
    title: "White-Glove Delivery",
    description: "Direct elite transport to your private estate or secure hangar.",
    icon: "PlaneTakeoff",
  },
  {
    id: "financing",
    title: "Tailored Funding",
    description: "Private high-line capitalization and custom acquisition paths.",
    icon: "Wallet",
  },
  {
    id: "warranty",
    title: "Extended Guarantee",
    description: "Multi-year comprehensive coverage on all engineered subsystems.",
    icon: "Hammer",
  },
  {
    id: "vip",
    title: "Priority Service",
    description: "Around-the-clock access to certified master technicians around the-globe.",
    icon: "UserCheck",
  },
];

export const luxuryCars: PremiumCar[] = [
  {
    id: "veltrix-apex",
    brand: "Veltrix",
    model: "Apex",
    tagline: "The Zenith of Horsepower",
    category: "Supercars",
    price: 2400000,
    featured: true,
    image: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Liquid Plasma Blue", hex: "#00e5ff", priceBonus: 0 },
      { name: "Shattered Platinum Carbon", hex: "#e5e7eb", priceBonus: 45000 },
      { name: "Apollo Gold Dust", hex: "#ffd700", priceBonus: 60000 },
      { name: "Veltrix Frozen Obsidian", hex: "#111111", priceBonus: 20000 },
    ],
    specifications: {
      acceleration: "1.43s",
      topSpeed: "280 mph",
      engine: "Quad-Motor Electric Core",
      power: "1,900 HP",
      range: "420 mi",
    },
    carbonFiberOptions: ["Exposed Gloss Carbon Layout", "Stealth Midnight Weave", "Infused Gold Carbon Trim"],
    detailedDescription: "The Apex represents the absolute pinnacle of electric propulsion. Engineered with an active aerospace carbon-silicon composite structure, four independent vectoring electronic motors distribute massive linear torque down to individual wheel quadrants in less than half a millisecond.",
    year: 2026,
  },
  {
    id: "lamborghini-revuelto",
    brand: "Lamborghini",
    model: "Revuelto V-spec",
    tagline: "The Hybrid Powerhouse",
    category: "Supercars",
    price: 890000,
    featured: true,
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Arancio Apex", hex: "#ff6600", priceBonus: 0 },
      { name: "Nero Enigma", hex: "#0c0c0c", priceBonus: 12000 },
      { name: "Verde Mantis Nebula", hex: "#39ff14", priceBonus: 25000 },
    ],
    specifications: {
      acceleration: "2.3s",
      topSpeed: "218 mph",
      engine: "6.5L V12 Plug-In Hybrid",
      power: "1,015 HP",
    },
    carbonFiberOptions: ["Revuelto Aero Weave Pack", "Aero Diffuser Extreme"],
    detailedDescription: "The plug-in hybrid supercar combining the raw high-RPM roar of a naturally aspirated 12-cylinder engine with triple high-torque electric active-drive motors. Commissioned with Veltrix elite aerodynamics custom chassis upgrades.",
    year: 2026,
  },
  {
    id: "ferrari-sf90",
    brand: "Ferrari",
    model: "SF90 Stradale",
    tagline: "Scuderia Mastery Reimagined",
    category: "Supercars",
    price: 750000,
    featured: true,
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Hyper Rosso Corsa", hex: "#cc0000", priceBonus: 0 },
      { name: "Giallo Solis", hex: "#ffcc00", priceBonus: 15000 },
      { name: "Sartorial Matte Graphite", hex: "#2b2b2b", priceBonus: 30000 },
    ],
    specifications: {
      acceleration: "2.4s",
      topSpeed: "211 mph",
      engine: "4.0L Twin-Turbo V8 Hybrid",
      power: "986 HP",
    },
    carbonFiberOptions: ["Scuderia Track Underbody", "Rear Wing Multi-flap Control"],
    detailedDescription: "A masterpiece of aerodynamic engineering. Features a custom triple-motor plug-in hybrid system paired with a highly responsive twin-turbocharged V8, fine-tuned by Veltrix specialized racing dynamics laboratory.",
    year: 2025,
  },
  {
    id: "porsche-gt3rs",
    brand: "Porsche",
    model: "911 GT3 RS Carbon",
    tagline: "Born On The Track, Custom Crafted",
    category: "Supercars",
    price: 340000,
    featured: true,
    image: "https://images.unsplash.com/photo-1611245041318-4730703d2740?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1611245041318-4730703d2740?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Acid Green Core", hex: "#a6ff00", priceBonus: 0 },
      { name: "Chalk Matte Metallic", hex: "#e5e7eb", priceBonus: 10000 },
      { name: "Satin Stealth Obsidian", hex: "#1c1c1c", priceBonus: 15000 },
    ],
    specifications: {
      acceleration: "2.9s",
      topSpeed: "184 mph",
      engine: "4.0L High-RPM Flat-Six",
      power: "518 HP",
    },
    carbonFiberOptions: ["Weissach Lightweight Package", "Active Wing Drag Reduction System"],
    detailedDescription: "Uncompromising motorsport technology. Driven by a legendary high-revving flat-six powerplant with fully active wing spoilers producing 1,895 lbs of downforce at top speeds.",
    year: 2026,
  },
  {
    id: "bmw-m5-competition",
    brand: "BMW",
    model: "M5 Competition (F90)",
    tagline: "The Ultimate Executive Drift Machine",
    category: "Sedans",
    price: 142000,
    featured: true,
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Marina Bay Blue Metallic", hex: "#0a3b8c", priceBonus: 0 },
      { name: "Frozen Deep Grey Matte", hex: "#4a4d50", priceBonus: 8500 },
      { name: "Alvite Grey Metallic", hex: "#5c5e62", priceBonus: 4500 },
      { name: "Snapper Rocks Blue", hex: "#008a99", priceBonus: 6000 },
    ],
    specifications: {
      acceleration: "2.9s",
      topSpeed: "190 mph",
      engine: "4.4L TwinPower V8 Twin-Scroll",
      power: "617 HP",
      range: "21 mpg",
    },
    carbonFiberOptions: ["M-Performance Rear Spoiler", "Carbon Kidney Grilles Overlay", "Carbon Roof & Aero Splitters"],
    detailedDescription: "The zenith of high-performance executive sedans, engineered with an active M xDrive system allowing instant transition between specialized 4WD and completely unlocked 2WD rear-wheel drift mode (DSC OFF). Complete with an active twin-turbo V8 producing 617 HP, Veltrix high-density drift telemetry, and volumetric V8 dual exhaust feedback.",
    year: 2025,
  },
  {
    id: "veltrix-phantom",
    brand: "Veltrix",
    model: "Phantom Bespoke",
    tagline: "A Royal Flight on Terrestrial Soil",
    category: "Sedans",
    price: 450000,
    featured: false,
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Emerald Aurum", hex: "#004b3e", priceBonus: 0 },
      { name: "Royal Graphite Duo-Tone", hex: "#3e3e42", priceBonus: 28000 },
      { name: "Sartorial Alabaster Silk", hex: "#fefefe", priceBonus: 18000 },
    ],
    specifications: {
      acceleration: "4.1s",
      topSpeed: "155 mph",
      engine: "6.75L Twin-Turbo Charged V12",
      power: "650 HP",
    },
    carbonFiberOptions: ["Champagne Console Matte Trim", "Veltrix Shield Armored Glass"],
    detailedDescription: "A fortress of quietude and high sovereign prestige. Engineered with dual-layered starlight acoustic insulation glass, hand-threaded French silk doors, integrated crystal mini-bar, and automatic levitating pneumatic glide suspension.",
    year: 2026,
  },
  {
    id: "veltrix-zenith",
    brand: "Veltrix",
    model: "Zenith EV",
    tagline: "Ultimate Terrain Hyper-Glide",
    category: "SUV",
    price: 185000,
    featured: false,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Stealth Platinum", hex: "#6b7280", priceBonus: 0 },
      { name: "Midnight Nebula Noir", hex: "#050b14", priceBonus: 5000 },
      { name: "Glacial Aurora Teal", hex: "#00a896", priceBonus: 12000 },
    ],
    specifications: {
      acceleration: "2.7s",
      topSpeed: "175 mph",
      engine: "Dual Electromagnet Hyper-Range",
      power: "1,000 HP",
      range: "450 mi",
    },
    carbonFiberOptions: ["Underbody Titanium Shield", "Active Terrestrial Air Glide Suspension"],
    detailedDescription: "The absolute state of the art in high-riding luxury. Features custom off-road magnetic vectoring, thermal night vision navigation, active ballistic safety glass elements, and hyper-rapid solid state electric architecture.",
    year: 2026,
  },
  {
    id: "tesla-roadster",
    brand: "Tesla",
    model: "Roadster Veltrix-X",
    tagline: "Defy Gravity with Flight Options",
    category: "Electric",
    price: 250000,
    featured: false,
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Plasma Blue Metallic", hex: "#1d4ed8", priceBonus: 0 },
      { name: "Liquid Chrome Red", hex: "#e11d48", priceBonus: 10000 },
      { name: "Carbon Warp Matte Noir", hex: "#000000", priceBonus: 18000 },
    ],
    specifications: {
      acceleration: "1.1s",
      topSpeed: "260 mph",
      engine: "Bespoke Tri-Motor Carbon-Wrapped",
      power: "1,200 HP",
      range: "620 mi",
    },
    carbonFiberOptions: ["Veltrix Active Rear Thruster Accents", "Carbon Aero Splat Pack"],
    detailedDescription: "A custom curated edition of the modular hypercar. Boosted acceleration utilizing localized performance energy management and a highly specialized interior.",
    year: 2026,
  },
  {
    id: "mercedes-amg-one",
    brand: "Mercedes AMG",
    model: "ONE Hyper-Elite",
    tagline: "The Actual Formula 1 Champion on Street",
    category: "Supercars",
    price: 2720000,
    featured: true,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1200",
    heroImage: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1200",
    colors: [
      { name: "Silver Arrow Liquid Chrome", hex: "#a0a0a0", priceBonus: 0 },
      { name: "Petronas Teal Contrast", hex: "#00a19c", priceBonus: 40000 },
    ],
    specifications: {
      acceleration: "2.8s",
      topSpeed: "219 mph",
      engine: "1.6L V6 Hybrid Turbo F1 Core",
      power: "1,063 HP",
    },
    carbonFiberOptions: ["Exposed Formula Roof Intake", "Active Front Diffuser Shutter Pack"],
    detailedDescription: "Unmatched integration of standard hyper-motors. Featuring raw championship-winning carbon fiber monocoques, multi-layer direct exhaust cooling, and fully adaptive F1 telemetry control systems.",
    year: 2026,
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: "1",
    name: "Alistair Sterling",
    role: "Collector",
    location: "Monaco",
    comment: "The acquisition of the Veltrix Apex was absolute perfection. Delivered directly to my estate. It truly drives beyond the heavens.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    vehicleAcquired: "Veltrix Apex",
  },
  {
    id: "2",
    name: "Dr. Seraphina Vance",
    role: "AI Architect",
    location: "Zurich",
    comment: "Veltrix's active quad-motor telemetry matches my expectations of high precision. This is a computer science masterpiece.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
    vehicleAcquired: "Tesla Roadster Veltrix-X",
  },
  {
    id: "3",
    name: "Marcus Thorne",
    role: "Investor",
    location: "Singapore",
    comment: "The Phantom Bespoke is not just a vehicle—it is secondary to none. Luxury travel has become my most productive hour.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200",
    vehicleAcquired: "Veltrix Phantom",
  },
];
